[package]
edition = "2021"
name = "libycresources"
version = "0.2.0"

[[example]]
name = "undat"

[[example]]
name = "fontview"

[[example]]
name = "frameview"

[[example]]
name = "protoview"

[dev-dependencies]
bmp = "0.5.0"
clap = "3.0.0-beta.5"
